### ISSUE TITLE
Implement Varint into transaction payload

### ISSUE THREAD

**Issue by Neylix** [aime-risson/archethic-python-sdk#6]
Hi ! 

The node implemented the Var int system to provide an almost infinite number of entry in a list. https://github.com/archethic-foundation/archethic-node/issues/408
This modification update the payload for transaction signature.

Python sdk have to add the Var int into the payload when signing a transaction.
Implementation done in libjs : https://github.com/archethic-foundation/libjs/pull/64

**Comment by herissondev** [comment]
Hi, I'll do the modifications that as soon as I can!

**Comment by herissondev** [comment]
Varint implementation done closed by #9
